title = "GAdminV2"  # From Git
gitRepoUrl = "https://github.com/gdr1461/GAdminV2" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "gdr1461"
projectName = "GAdmin"
url = "https://gdr1461.github.io"
baseUrl = "/GAdminV2"
tagline = "Admin Panel"

[footer]
style = "dark"
copyright = "Copyright © 2025 gdr1461. Built with Moonwave and Docusaurus"